AcmeFacturacionBundle_validar:
    pattern:  /facturacion/validar
    defaults: { _controller: AcmeFacturacionBundle:Default:validar }

AcmeFacturacionBundle_homepage:
    pattern:  /factura
    defaults: { _controller: AcmeFacturacionBundle:Default:index }

AcmeFacturacionBundle_verpdf:
    pattern:  /factura/verpdf/{factura_id}/
    defaults: { _controller: AcmeFacturacionBundle:Default:verpdf}

AcmeFacturacionBundle_importar:
    pattern:  /factura/importar
    defaults: { _controller: AcmeFacturacionBundle:FacturaAdmin:importar, _sonata_admin: acme.blog.admin.factura}

AcmeFacturacionBundle_template:
    pattern:  /template
    defaults: { _controller: AcmeFacturacionBundle:Default:template }

AcmeFacturacionBundle_getTemplatesJson:
    pattern:  /templates/getTemplatesJson
    defaults: { _controller: AcmeFacturacionBundle:Default:getTemplatesJson}