parameters:
#    acme_facturacion.example.class: Acme\FacturacionBundle\Example

services:
#    acme_facturacion.example:
#        class: %acme_facturacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
