imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator: ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
#            - 'AcmeBlogBundle:Form:faary.html.twig'
            - 'AcmeBlogBundle:Form:form_without_table.html.twig'
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text		

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
# app/config/config.yml
sonata_admin:
    dashboard:
        
services:
   acme.blog.admin.blog:
      class: Acme\BlogBundle\Admin\BlogAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Blog, label: Blog }
      arguments: [null, Acme\BlogBundle\Entity\Blog, AcmeBlogBundle:BlogAdmin]
   acme.blog.admin.categoria:
      class: Acme\BlogBundle\Admin\CategoriaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Blog, label: Categoria }
      arguments: [null, Acme\BlogBundle\Entity\Categoria, AcmeBlogBundle:CategoriaAdmin]
   acme.blog.admin.post:
      class: Acme\BlogBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Blog, label: Post }
      arguments: [null, Acme\BlogBundle\Entity\Post, AcmeBlogBundle:PostAdmin]
   #------------------------------------------------- Facturacion
   acme.blog.admin.factura:
      class: Acme\FacturacionBundle\Admin\FacturaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Facturacion, label: Factura }
      arguments: [null, Acme\FacturacionBundle\Entity\Factura, AcmeFacturacionBundle:FacturaAdmin]  
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User