AcmeFacturacionBundle:
    resource: "@AcmeFacturacionBundle/Resources/config/routing.yml"
    prefix:   /

#AcmeHealthyBundle:
#    resource: "@AcmeHealthyBundle/Resources/config/routing.yml"
#    prefix:   /

AcmeBlogBundle:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

#AcmeUserBundle:
#    resource: "@AcmeUserBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
