security:
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext
         Acme\UserBundle\Entity\User:
             algorithm: sha1
             encode_as_base64: false
             iterations: 1
    

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    #providers:
    #    administrators:
    #        entity: { class: AcmeUserBundle:User, property: username }
    providers:
        chain_provider:
            providers: [in_memory, user_db]
        user_db:
            entity: { class: AcmeUserBundle:User, property: username }
        in_memory:
            users:
                user:  { password: userpass,  roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:       #Authentication
        secured_area:
            pattern:  ^/
            anonymous: ~
            form_login: ~               
            logout:
                path:   /logout
                target: /blog

    access_control: #Authorization
        - { path: /new_blog, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }