blog_home:
    pattern:  /blog
    defaults: { _controller: AcmeBlogBundle:Default:home}

blog_index:
    pattern:  /blog/{blog}
    defaults: { _controller: AcmeBlogBundle:Default:index}

post:
    pattern:  /blog/{blog}/{post}
    defaults: { _controller: AcmeBlogBundle:Default:post}